name: 'Aptos Devnet Autodeploy action'
description: 'Helps keep packages deployed to Aptos devnet'
author: 'Brian Li'
inputs:
  publish_command:
    description: 'Command to publish the package'
    required: true
  check_address:
    description: 'Address to check for the published package'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Run publish check
      run: ./publish-check.sh
      env:
        PUBLISH_COMMAND: ${{ inputs.publish_command }}
        CHECK_ADDRESS: ${{ inputs.check_address }}
      shell: bash
branding:
  icon: 'check-circle'
  color: 'green'
