name: 'Aptos Devnet Autodeploy action'
description: 'Helps keep packages deployed to Aptos devnet'
author: 'Brian Li'
inputs:
  package_dir:
    description: 'Directory containing the package to publish'
    required: true
  named_addresses:
    description: 'Named addresses to publish the package with'
    required: false
  private_key:
    description: 'Private key to publish the package with'
    required: true
  upgrade_allowed:
    description: 'Whether to allow upgrades'
    type: boolean
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: Run publish check
      run: nix-shell --command './publish-check.sh'
      env:
        PACKAGE_DIR: ${{ inputs.package_dir }}
        NAMED_ADDRESSES: ${{ inputs.named_addresses }}
        PRIVATE_KEY: ${{ inputs.private_key }}
        UPGRADE_ALLOWED: ${{ inputs.upgrade_allowed }}
      shell: bash
branding:
  icon: 'check-circle'
  color: 'green'
