name: "Aptos Devnet Autodeploy action"
description: "Helps keep packages deployed to Aptos devnet"
author: "Brian Li"
inputs:
  package_dir:
    description: "Directory containing the package to publish"
    required: true
  check_address:
    description: "Address to check for the package"
    required: true
  named_addresses:
    description: "Named addresses to publish the package with"
    required: false
  private_key:
    description: "Private key to publish the package with"
    required: true
  upgrade_allowed:
    description: "Whether to allow upgrades"
    type: boolean
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Aptos CLI
      run: curl -fsSL "https://aptos.dev/scripts/install_cli.py" | python3
      shell: bash
    - name: Run publish check
      run: "${{ github.action_path }}/publish-check.sh"
      env:
        ACTION_PATH: ${{ github.action_path }}
        PACKAGE_DIR: ${{ inputs.package_dir }}
        CHECK_ADDRESS: ${{ inputs.check_address }}
        NAMED_ADDRESSES: ${{ inputs.named_addresses }}
        PRIVATE_KEY: ${{ inputs.private_key }}
        UPGRADE_ALLOWED: ${{ inputs.upgrade_allowed }}
      shell: bash
branding:
  icon: "check-circle"
  color: "green"
