name: Publish Check

on:
  schedule:
    - cron: '*/15 * * * *' # Replace 15 with your desired interval in minutes

jobs:
  devnet-autodeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Publish
        uses: ./ # Uses an action in the root of the repository
        with:
          publish_command: |
            aptos move publish \
            --package-dir example/aptos-devnet-autodeploy \
            --named-addresses module_addr="0x3cb93ebcabdb73a76c23df00c3176a14efe64b948ca4b319f88561068e77df2d" \
            --private-key="0x4c60f5dd12731c08b1a74410845668e2f063fbc9b0029966a26f59094983e578" \
            --url="https://fullnode.devnet.aptoslabs.com/" \
            --assume-yes
          check_address: 0x3cb93ebcabdb73a76c23df00c3176a14efe64b948ca4b319f88561068e77df2d
